"""`plans/mock-flight-fixture/plan.md`: a deterministic, fixture-driven
replay of `tests/fixtures/mock_flight_canonical.json` through the real
aircraft-layer HTTP wire shape (`tests/support/mock_aircraft_layer.
MockAircraftLayerServer`), the real body-layer perception/belief pipeline
(`logger._build_sources` + `logger.ConsolePerceptionRunner`), and a real
synthetic world-model store (`tests/support/mock_world_model`), asserting
the whole chain reaches a known `belief.contacts.ContactStore` end state.

This is the one test in this suite that exercises the full chain a single
source-plus-`ContactStore` fixture test (`test_emission_pipeline.py`) or a
pure-belief fixture test (`test_contacts.py`) structurally cannot: two real
sources sharing one poll's HTTP round trip, a real (if flat/synthetic)
terrain LOS gate instead of a monkeypatched `visibility.
line_of_sight_clear`, and -- in the second test below -- the real
`--console` threading model (`logger._run_console_poll_loop` on a
background thread, `belief.console.Console` dispatch on the foreground
thread), catching the class of cross-thread `sqlite3.ProgrammingError` bug
`test_logger.py`'s own Stage 6/BL-5 regression tests were written for, but
now against two sources and many consecutive polls instead of one.

**Only a wiring proof, not a terrain-accuracy claim** -- see
`tests/support/mock_world_model.py`'s own docstring: the synthetic store's
flat, low elevation grid makes every line-of-sight check in this fixture
clear by construction. Real-terrain LOS correctness is the World Model
Builder's own control-point tests' job.

**Fixture intent** (`tests/fixtures/mock_flight_canonical.json`, 20 poll
frames, generated by converting known DCS x/z positions through the real
world-model `coordinates.dcs_to_wgs84` -- no monkeypatched coordinate
transform, per the plan's decision to exercise real geometry end to end):

- Ownship flies a straight track due north (heading 0 deg true) from DCS
  `(x=0, z=0)` to `(x=1140, z=0)`, climbing/descending never -- constant
  700 m MSL, t_sim advancing 5 s/poll.
- **`object_id=101`, `"Ural-375"` (DCS reporting name `"Ural truck"`),
  stationary at `(x=1400, z=0, alt=500)`, dead ahead the whole flight.**
  This is the plan's "continuously visible and stationary" object (the
  duplicate-contact regression shape). The Hybrid channel detects it every
  poll from frame 0 (`petrovich_indication.fields.middle_list_text ==
  "Ural truck"` in every frame, always in range/forward hemisphere),
  founding a `TYPE`-level `"Ural truck"` contact immediately; the naked-eye
  channel also tracks it every poll (through frame 15, see below), but --
  **as of 2026-09-20's final scope change** (`plans/detection-cones-slice1/
  plan.md`: `check_visibility`'s default optic moved to `UNAIDED_OPTIC`,
  M=1.0, not `BINOCULAR_OPTIC`) -- **never above `lowres` tier**. At
  M=1.0 a 6 m truck's `medres` threshold is 428.57 m and `hires` is
  214.29 m; the closest this fixture's own track ever gets to the truck
  is ~260 m ground range at frame 19, and by then the naked-eye channel
  has already dropped the truck entirely (the cockpit mask cutoff below).
  So the naked-eye truck percept is `lowres`/`OP_GROUPSOMETHING` on every
  poll it appears, never `medres`/`"OP_TRUCK"` -- confirmed by actually
  running the harness, not derived on paper. `belief.classification.
  fold_classification`'s "lower level holds" rule (a same- or
  coarser-level claim never downgrades an already-established finer one)
  means every one of those `lowres` percepts folds into Hybrid's
  already-`TYPE`-level contact without changing what's held -- no
  `CONTACT_CLASSIFICATION_CHANGED` event, same as before this change,
  though for a different underlying reason (the naked-eye percept was
  always coarser than Hybrid's, not merely never finer).
- **`object_id=102`, `"Infantry AK"` (reporting name `"Soldier AK"`),
  stationary at `(x=1800, z=0, alt=500)`.** The plan's "appears mid-flight"
  object: present in `world_objects` ground truth from frame 0 (DCS ground
  truth is never gated), and was naked-eye-visible for at least part of
  the flight under every earlier multiplier this slice tried (M=4.0,
  M=8.0).

  **As of 2026-09-20's final scope change, it is never naked-eye-visible
  at all, for the whole fixture.** At the new default (`UNAIDED_OPTIC`,
  M=1.0) a 1.8 m object's `lowres` threshold is only 600 m; this object's
  closest approach across the entire 20-frame track is ~660 m ground
  range at the final frame (slant range ~689 m, per the same calculation
  the previous multiplier passes already worked out) -- still outside
  600 m. Object 102 therefore **never becomes a contact in this fixture
  any more** -- confirmed by actually running the harness (this file's
  own stated convention), not assumed from the range arithmetic alone.
  This is a real, large behavioural consequence of the naked-eye-default
  change (see `visibility.py`'s own module docstring on why it was made)
  reflected directly in this integration fixture, not something to
  "fix" by moving the object closer -- the fixture's own positions are
  real DCS coordinates run through the real coordinate transform (see
  below) and are not this test's to edit.

Exact per-frame range/tier numbers were computed by a throwaway script
against the real formulas in `perception.visibility`/`perception.geometry`
before authoring the fixture (not guessed) -- see
`plans/mock-flight-fixture/implementation.md` for that derivation. The
`ContactStore` end-state assertions below were derived by actually running
this harness once and inspecting its output (per the plan's explicit
instruction not to guess-then-backfill), then sanity-checked against the
intent above.
"""

from __future__ import annotations

import io
import json
import sys
import threading
import time
from pathlib import Path
from typing import Any

from support.mock_aircraft_layer import MockAircraftLayerServer
from support.mock_world_model import build_mock_world_model

from aircraft_client import AircraftLayerClient
from belief.console import Console
from belief.tools import describe_contact, get_contacts
from logger import (
    ConsolePerceptionRunner,
    _build_sources,
    _run_console_poll_loop,
    _run_console_repl,
)
from perception.geometry import GeoPosition, line_of_sight_clear, open_world_model

_THEATRE = "Syria"
_FIXTURE_PATH = Path(__file__).parent / "fixtures" / "mock_flight_canonical.json"
#: Generous but bounded -- a hard failure (not a skip) if the background
#: poll thread hasn't finished within this window, per the plan's Risks
#: section ("flaky-but-passing is worse than a clear timeout failure here").
_THREAD_JOIN_TIMEOUT_S = 10.0


def _load_frames() -> list[dict[str, Any]]:
    return json.loads(_FIXTURE_PATH.read_text())  # type: ignore[no-any-return]


# --- Mock server: frame-advance correctness ---------------------------------
#
# The plan's specific correctness risk: within one poll, both sources call
# get_world_objects_latest()/get_petrovich_indication_latest() after the
# runner has already called get_telemetry_latest() once -- if the server
# advanced its index on every GET, the two calls could observe different
# poll frames. This drives the real AircraftLayerClient against a tiny
# hand-built 2-frame sequence to prove that never happens, before trusting
# it under the full 20-frame fixture below.


def test_mock_server_advances_frame_index_only_on_telemetry_poll() -> None:
    frames = [
        {
            "telemetry": {"marker": "t0"},
            "world_objects": {"marker": "w0"},
            "petrovich_indication": {"marker": "p0"},
        },
        {
            "telemetry": {"marker": "t1"},
            "world_objects": {"marker": "w1"},
            "petrovich_indication": {"marker": "p1"},
        },
    ]
    server = MockAircraftLayerServer(frames)
    url = server.start()
    try:
        client = AircraftLayerClient(base_url=url)

        assert client.get_telemetry_latest() == {"marker": "t0"}
        # Both endpoints mirror frame 0 regardless of call count, since no
        # further /telemetry/latest poll has happened yet.
        assert client.get_world_objects_latest() == {"marker": "w0"}
        assert client.get_world_objects_latest() == {"marker": "w0"}
        assert client.get_petrovich_indication_latest() == {"marker": "p0"}

        assert client.get_telemetry_latest() == {"marker": "t1"}
        assert client.get_world_objects_latest() == {"marker": "w1"}
        assert client.get_petrovich_indication_latest() == {"marker": "p1"}

        # Exhausted -- holds at the last frame rather than erroring or
        # wrapping around.
        assert client.get_telemetry_latest() == {"marker": "t1"}
        assert client.get_telemetry_latest() == {"marker": "t1"}
        assert client.get_world_objects_latest() == {"marker": "w1"}
        assert client.get_petrovich_indication_latest() == {"marker": "p1"}
    finally:
        server.stop()


# --- Synthetic world-model fixture: LOS gate sanity -------------------------


def test_mock_world_model_line_of_sight_clear_over_flat_terrain(
    tmp_path: Path,
) -> None:
    db_path = tmp_path / "region.sqlite"
    build_mock_world_model(db_path)
    conn = open_world_model(db_path)
    try:
        observer = GeoPosition(x=0.0, z=0.0, alt_m=700.0)
        target = GeoPosition(x=1400.0, z=0.0, alt_m=500.0)
        assert line_of_sight_clear(conn, _THEATRE, observer, target)
    finally:
        conn.close()


# --- Single-threaded full-chain determinism test ----------------------------


def test_mock_flight_chain_single_threaded_reaches_expected_contact_state(
    tmp_path: Path,
) -> None:
    frames = _load_frames()
    world_model_db = tmp_path / "region.sqlite"
    build_mock_world_model(world_model_db)
    world_model_conn = open_world_model(world_model_db)
    server = MockAircraftLayerServer(frames)
    url = server.start()
    try:
        aircraft_client = AircraftLayerClient(base_url=url)
        sources = _build_sources(
            aircraft_client, _THEATRE, world_model_conn, emit_mode="every_poll"
        )
        runner = ConsolePerceptionRunner(
            aircraft_client=aircraft_client, sources=sources
        )

        for _ in frames:
            runner.run_once()

        final_t_sim = frames[-1]["telemetry"]["dcs_model_time_s"]
        assert runner.last_t_sim == final_t_sim

        # **Rewritten 2026-09-20** (`plans/detection-cones-slice1/plan.md`,
        # final scope change: `check_visibility`'s default optic moved to
        # `UNAIDED_OPTIC`, M=1.0). Object 102 (infantry) is never
        # naked-eye-visible anywhere in this fixture at the new default
        # (module docstring's object-102 bullet has the range arithmetic)
        # -- confirmed by actually running the pipeline poll-by-poll, not
        # guessed:
        #
        # - Polls 0-15: naked-eye emits exactly 1 observation per poll --
        #   object 101 (the truck), `lowres`/`OP_GROUPSOMETHING` the whole
        #   time (see the module docstring's object-101 bullet: this
        #   fixture's own track never gets close enough to the truck for
        #   naked-eye to reach `medres`/`hires` before the mask cuts it off).
        #   16 naked-eye observations.
        # - Polls 16-19: object 101 drops out of the naked-eye channel
        #   entirely -- the cockpit occlusion mask cutoff (x ~ 905),
        #   unrelated to this change. 0 naked-eye observations.
        #
        # Naked-eye: 16. Hybrid: 20 (object 101, every poll, unaffected --
        # Hybrid never clusters, has no elevation gate, and does not use
        # `check_visibility` at all). 16 + 20 = 36.
        #
        # Object 102 never appearing on any channel means the same-poll
        # co-fold exclusion (`belief.contacts.ContactStore.ingest`'s
        # pre-scan, `plans/group-contact-model/plan.md` Stage 3a) has
        # nothing to exclude here any more -- there is only ever one
        # candidate contact in this fixture.
        assert len(runner.store.observations) == 36

        contacts = get_contacts(runner.store, final_t_sim)

        # ONE contact now, not two -- `CONTACT_1` (Hybrid's founding
        # percept, frame 0), the truck: both sources, `type`-level
        # `"Ural truck"`. There is no `CONTACT_2` any more (see above).
        assert len(contacts) == 1

        # One founding CONTACT_DETECTED -- no spurious CONTACT_LOST/
        # REACQUIRED (the truck is continuously visible to Hybrid once
        # acquired) and no CONTACT_CLASSIFICATION_CHANGED (see the module
        # docstring's "lower level holds" note -- Hybrid's frame-0
        # TYPE-level percept already establishes the truck contact, and
        # every naked-eye percept of it is `lowres`, strictly coarser, so
        # it folds in without changing what's held).
        assert [event.kind for event in runner.store.events] == [
            "CONTACT_DETECTED",
        ]

        truck = next(c for c in contacts if c["facts"]["id"] == "CONTACT_1")
        assert truck["facts"]["classification"]["value"] == "Ural truck"
        assert truck["facts"]["classification"]["level"] == "type"
        assert truck["facts"]["certainty"] == "observed"
        assert sorted(truck["facts"]["sources"]) == [
            "naked_eye_visual_filtered",
            "petrovich_detection_associated",
        ]

        # `CONTACT_1`'s cardinality: every naked-eye report of the truck is
        # a singleton `OP_1UNIT`, poll after poll, so `fold_cardinality`
        # never sees a disjoint reading to contradict against and the
        # contact holds `(1, 1)` throughout.
        truck_cardinality = truck["facts"]["cardinality"]
        assert (truck_cardinality["lo"], truck_cardinality["hi"]) == (1, 1)

        described = describe_contact(runner.store, truck["facts"]["id"], final_t_sim)
        assert described is not None
        assert described["facts"]["id"] == truck["facts"]["id"]
    finally:
        server.stop()
        world_model_conn.close()


# --- Threaded console/REPL smoke test ---------------------------------------


def test_mock_flight_chain_threaded_console_smoke(tmp_path: Path) -> None:
    """Runs the real `--console` threading model against the same fixture:
    `_run_console_poll_loop` on a background thread (mirroring `main()`'s
    `--console` wiring exactly, including opening its own thread-local
    `sqlite3.Connection`), while the foreground thread dispatches REPL
    commands via `belief.console.Console`/`_run_console_repl` against the
    same store. Asserts no exception crosses either thread -- this is the
    test that would have caught the cross-thread `sqlite3.ProgrammingError`
    class of bug (`test_logger.py`'s Stage 6/BL-5 regression tests cover the
    single-poll case; this drives the same real functions across the whole
    20-frame fixture)."""
    frames = _load_frames()
    world_model_db = tmp_path / "region.sqlite"
    build_mock_world_model(world_model_db)
    server = MockAircraftLayerServer(frames)
    url = server.start()
    try:
        aircraft_client = AircraftLayerClient(base_url=url)
        runner = ConsolePerceptionRunner(aircraft_client=aircraft_client)
        stop_event = threading.Event()
        poll_thread = threading.Thread(
            target=_run_console_poll_loop,
            args=(
                runner,
                aircraft_client,
                _THEATRE,
                world_model_db,
                0.01,  # tiny poll interval -- exhausts all 20 frames quickly
                stop_event,
            ),
            daemon=True,
        )
        poll_thread.start()
        try:
            # Let the poll thread consume every fixture frame (the mock
            # server holds at the last frame once exhausted, so waiting for
            # last_t_sim to reach the final frame's t_sim is a reliable
            # "all frames consumed" signal, not a race on poll count).
            final_t_sim = frames[-1]["telemetry"]["dcs_model_time_s"]
            deadline = time.monotonic() + _THREAD_JOIN_TIMEOUT_S
            while runner.last_t_sim != final_t_sim and time.monotonic() < deadline:
                time.sleep(0.02)
            assert runner.last_t_sim == final_t_sim, (
                "poll thread did not reach the fixture's final frame within "
                f"{_THREAD_JOIN_TIMEOUT_S}s"
            )

            output = io.StringIO()
            console = Console(store=runner.store, output=output)
            # `_run_console_repl` reads sys.stdin line-by-line until EOF --
            # mirrors test_logger.py's own monkeypatched-stdin pattern.
            stdin = io.StringIO("contacts\nshow CONTACT_1\n")
            real_stdin = sys.stdin
            sys.stdin = stdin
            try:
                _run_console_repl(runner, console, world_model_db, _THEATRE)
            finally:
                sys.stdin = real_stdin
        finally:
            stop_event.set()
            poll_thread.join(timeout=_THREAD_JOIN_TIMEOUT_S)

        assert not poll_thread.is_alive(), (
            f"poll thread failed to stop within {_THREAD_JOIN_TIMEOUT_S}s"
        )

        repl_output = output.getvalue()
        assert "sqlite3.ProgrammingError" not in repl_output
        assert repl_output.strip() != ""
    finally:
        server.stop()
