"""`plans/mock-flight-fixture/plan.md`: a deterministic, fixture-driven
replay of `tests/fixtures/mock_flight_canonical.json` through the real
aircraft-layer HTTP wire shape (`tests/support/mock_aircraft_layer.
MockAircraftLayerServer`), the real body-layer perception/belief pipeline
(`logger._build_sources` + `logger.ConsolePerceptionRunner`), and a real
synthetic world-model store (`tests/support/mock_world_model`), asserting
the whole chain reaches a known `belief.contacts.ContactStore` end state.

This is the one test in this suite that exercises the full chain a single
source-plus-`ContactStore` fixture test (`test_emission_pipeline.py`) or a
pure-belief fixture test (`test_contacts.py`) structurally cannot: two real
sources sharing one poll's HTTP round trip, a real (if flat/synthetic)
terrain LOS gate instead of a monkeypatched `visibility.
line_of_sight_clear`, and -- in the second test below -- the real
`--console` threading model (`logger._run_console_poll_loop` on a
background thread, `belief.console.Console` dispatch on the foreground
thread), catching the class of cross-thread `sqlite3.ProgrammingError` bug
`test_logger.py`'s own Stage 6/BL-5 regression tests were written for, but
now against two sources and many consecutive polls instead of one.

**Only a wiring proof, not a terrain-accuracy claim** -- see
`tests/support/mock_world_model.py`'s own docstring: the synthetic store's
flat, low elevation grid makes every line-of-sight check in this fixture
clear by construction. Real-terrain LOS correctness is the World Model
Builder's own control-point tests' job.

**Fixture intent** (`tests/fixtures/mock_flight_canonical.json`, 20 poll
frames, generated by converting known DCS x/z positions through the real
world-model `coordinates.dcs_to_wgs84` -- no monkeypatched coordinate
transform, per the plan's decision to exercise real geometry end to end):

- Ownship flies a straight track due north (heading 0 deg true) from DCS
  `(x=0, z=0)` to `(x=1140, z=0)`, climbing/descending never -- constant
  700 m MSL, t_sim advancing 5 s/poll.
- **`object_id=101`, `"Ural-375"` (DCS reporting name `"Ural truck"`),
  stationary at `(x=1400, z=0, alt=500)`, dead ahead the whole flight.**
  This is the plan's "continuously visible and stationary" object (the
  duplicate-contact regression shape). The Hybrid channel detects it every
  poll from frame 0 (`petrovich_indication.fields.middle_list_text ==
  "Ural truck"` in every frame, always in range/forward hemisphere),
  founding a `TYPE`-level `"Ural truck"` contact immediately; the naked-eye
  channel also tracks it every poll, starting at `medres` tier (class-level
  `"OP_TRUCK"`, range ~1414 m) and crossing the `hires` threshold (1200 m)
  at frame 4. **Running the harness once (not guessed) showed this does
  not produce a mid-flight `CONTACT_CLASSIFICATION_CHANGED` event**: Hybrid's
  frame-0 percept already establishes the contact at `TYPE` level, and
  `belief.classification.fold_classification`'s "lower level holds" rule
  (a same- or coarser-level claim never downgrades an already-established
  finer one) means every later naked-eye `CLASS`-level percept -- both
  before and after its own `medres`->`hires` crossing -- folds in without
  changing the contact's held classification at all. This is real, correct
  behavior worth documenting rather than the reclassification-event scenario
  originally sketched for this object: it demonstrates the classification
  lattice's monotonicity *and* cross-channel correlation onto one contact
  (never two) at the same time, which is exactly what a duplicate-contact
  regression test needs.
- **`object_id=102`, `"Infantry AK"` (reporting name `"Soldier AK"`),
  stationary at `(x=1800, z=0, alt=500)`.** The plan's "appears mid-flight"
  object: present in `world_objects` ground truth from frame 0 (DCS ground
  truth is never gated), but outside the naked-eye visibility gate's range
  threshold (~1674 m) until frame 3, when the shrinking ownship-to-object
  range first clears it -- `lowres` tier initially, refining to `medres` by
  frame 16 as range keeps shrinking. Never referenced by
  `petrovich_indication` text, so it is naked-eye-only, unlike object 101 --
  this is what keeps the fixture's Hybrid-channel behavior simple to reason
  about (exactly one classification text, `"Ural truck"`, ever appears on
  that channel).

Exact per-frame range/tier numbers were computed by a throwaway script
against the real formulas in `perception.visibility`/`perception.geometry`
before authoring the fixture (not guessed) -- see
`plans/mock-flight-fixture/implementation.md` for that derivation. The
`ContactStore` end-state assertions below were derived by actually running
this harness once and inspecting its output (per the plan's explicit
instruction not to guess-then-backfill), then sanity-checked against the
intent above.
"""

from __future__ import annotations

import io
import json
import sys
import threading
import time
from pathlib import Path
from typing import Any

from support.mock_aircraft_layer import MockAircraftLayerServer
from support.mock_world_model import build_mock_world_model

from aircraft_client import AircraftLayerClient
from belief.console import Console
from belief.tools import describe_contact, get_contacts
from logger import (
    ConsolePerceptionRunner,
    _build_sources,
    _run_console_poll_loop,
    _run_console_repl,
)
from perception.geometry import GeoPosition, line_of_sight_clear, open_world_model

_THEATRE = "Syria"
_FIXTURE_PATH = Path(__file__).parent / "fixtures" / "mock_flight_canonical.json"
#: Generous but bounded -- a hard failure (not a skip) if the background
#: poll thread hasn't finished within this window, per the plan's Risks
#: section ("flaky-but-passing is worse than a clear timeout failure here").
_THREAD_JOIN_TIMEOUT_S = 10.0


def _load_frames() -> list[dict[str, Any]]:
    return json.loads(_FIXTURE_PATH.read_text())  # type: ignore[no-any-return]


# --- Mock server: frame-advance correctness ---------------------------------
#
# The plan's specific correctness risk: within one poll, both sources call
# get_world_objects_latest()/get_petrovich_indication_latest() after the
# runner has already called get_telemetry_latest() once -- if the server
# advanced its index on every GET, the two calls could observe different
# poll frames. This drives the real AircraftLayerClient against a tiny
# hand-built 2-frame sequence to prove that never happens, before trusting
# it under the full 20-frame fixture below.


def test_mock_server_advances_frame_index_only_on_telemetry_poll() -> None:
    frames = [
        {
            "telemetry": {"marker": "t0"},
            "world_objects": {"marker": "w0"},
            "petrovich_indication": {"marker": "p0"},
        },
        {
            "telemetry": {"marker": "t1"},
            "world_objects": {"marker": "w1"},
            "petrovich_indication": {"marker": "p1"},
        },
    ]
    server = MockAircraftLayerServer(frames)
    url = server.start()
    try:
        client = AircraftLayerClient(base_url=url)

        assert client.get_telemetry_latest() == {"marker": "t0"}
        # Both endpoints mirror frame 0 regardless of call count, since no
        # further /telemetry/latest poll has happened yet.
        assert client.get_world_objects_latest() == {"marker": "w0"}
        assert client.get_world_objects_latest() == {"marker": "w0"}
        assert client.get_petrovich_indication_latest() == {"marker": "p0"}

        assert client.get_telemetry_latest() == {"marker": "t1"}
        assert client.get_world_objects_latest() == {"marker": "w1"}
        assert client.get_petrovich_indication_latest() == {"marker": "p1"}

        # Exhausted -- holds at the last frame rather than erroring or
        # wrapping around.
        assert client.get_telemetry_latest() == {"marker": "t1"}
        assert client.get_telemetry_latest() == {"marker": "t1"}
        assert client.get_world_objects_latest() == {"marker": "w1"}
        assert client.get_petrovich_indication_latest() == {"marker": "p1"}
    finally:
        server.stop()


# --- Synthetic world-model fixture: LOS gate sanity -------------------------


def test_mock_world_model_line_of_sight_clear_over_flat_terrain(
    tmp_path: Path,
) -> None:
    db_path = tmp_path / "region.sqlite"
    build_mock_world_model(db_path)
    conn = open_world_model(db_path)
    try:
        observer = GeoPosition(x=0.0, z=0.0, alt_m=700.0)
        target = GeoPosition(x=1400.0, z=0.0, alt_m=500.0)
        assert line_of_sight_clear(conn, _THEATRE, observer, target)
    finally:
        conn.close()


# --- Single-threaded full-chain determinism test ----------------------------


def test_mock_flight_chain_single_threaded_reaches_expected_contact_state(
    tmp_path: Path,
) -> None:
    frames = _load_frames()
    world_model_db = tmp_path / "region.sqlite"
    build_mock_world_model(world_model_db)
    world_model_conn = open_world_model(world_model_db)
    server = MockAircraftLayerServer(frames)
    url = server.start()
    try:
        aircraft_client = AircraftLayerClient(base_url=url)
        sources = _build_sources(
            aircraft_client, _THEATRE, world_model_conn, emit_mode="every_poll"
        )
        runner = ConsolePerceptionRunner(
            aircraft_client=aircraft_client, sources=sources
        )

        for _ in frames:
            runner.run_once()

        final_t_sim = frames[-1]["telemetry"]["dcs_model_time_s"]
        assert runner.last_t_sim == final_t_sim

        # 20 Hybrid observations (object 101, every poll) + 36 naked-eye
        # observations -- every one of those 56 percepts must land in
        # exactly two contacts below, not a duplicate-contact runaway across
        # so many consecutive polls.
        #
        # Was 53 before the 2026-09-17 screenshot calibration of
        # `visibility.py`'s angular-radius constants. Object 102 is
        # "Infantry AK" parked at x=1800: the old `lowres` threshold put
        # infantry at 1674 m, so it stayed invisible until ownship closed
        # inside that, while the calibrated threshold reaches 2400 m
        # (1.8 / 0.003 * 4.0) and picks it up from the first poll instead.
        # Three extra polls, three extra observations, same two contacts.
        #
        # Was 57 before the cockpit occlusion mask (`perception.
        # cockpit_mask`, 2026-09-17). Object 101 now drops out of the
        # *naked-eye* channel for the last few polls, which is the mask
        # working rather than a regression: ownship cruises at 700 m toward
        # a target at 500 m, so as the horizontal range closes the target's
        # depression steepens past the co-pilot's measured 22 deg forward
        # allowance -- 200 m of height difference exceeds 22 deg once the
        # horizontal range drops below ~495 m, i.e. once ownship passes
        # x ~ 905 of its 0 -> 1140 run. It goes under the nose, exactly as
        # it would in the real cockpit.
        #
        # The Hybrid channel is deliberately unaffected: the mask gates
        # `perception.visibility` (naked-eye) only, and Hybrid's own
        # forward-hemisphere filter in `perception.association` has no
        # elevation term. Object 102 (further out at x=1800) never closes
        # enough to be occluded and keeps all 17.
        assert len(runner.store.observations) == 56

        contacts = get_contacts(runner.store, final_t_sim)

        # Two contacts, as there are two real objects. This was ONE contact
        # between the 2026-09-17 vision calibration and the presence-tier merge
        # veto: the wider detection envelope made object 102 first visible at a
        # range where the naked-eye channel is structurally class-blind
        # (everything is OP_GROUPSOMETHING), so the class gate could not
        # discriminate and the honestly-wide spatial gate merged two genuinely
        # different objects. See plans/contact-merge-undercount/debug.md.
        assert len(contacts) == 2

        # One founding CONTACT_DETECTED per real object -- no spurious
        # CONTACT_LOST/REACQUIRED (both stay continuously visible once
        # acquired) and no CONTACT_CLASSIFICATION_CHANGED on object 101 (see
        # the module docstring's "lower level holds" note).
        assert [event.kind for event in runner.store.events] == [
            "CONTACT_DETECTED",
            "CONTACT_DETECTED",
        ]

        truck = next(
            c for c in contacts if c["facts"]["classification"]["value"] == "Ural truck"
        )
        assert truck["facts"]["classification"]["level"] == "type"
        assert truck["facts"]["certainty"] == "observed"
        assert sorted(truck["facts"]["sources"]) == [
            "naked_eye_visual_filtered",
            "petrovich_detection_associated",
        ]

        infantry = next(
            c for c in contacts if c["facts"]["classification"]["value"] != "Ural truck"
        )
        # Presence, not class -- and that is the calibrated behaviour, not a
        # shortfall. Object 102 is infantry (1.8 m), whose class threshold is
        # 1.8 / 0.014 * 4 = 514 m since the 2026-09-17 calibration; ownship
        # ends the fixture ~690 m away, so it never closes enough to resolve a
        # class. Before that calibration the threshold was 900 m and this
        # asserted OP_INFANTRY at class level.
        assert infantry["facts"]["classification"]["level"] == "presence"
        assert infantry["facts"]["sources"] == ["naked_eye_visual_filtered"]

        described = describe_contact(runner.store, truck["facts"]["id"], final_t_sim)
        assert described is not None
        assert described["facts"]["id"] == truck["facts"]["id"]
    finally:
        server.stop()
        world_model_conn.close()


# --- Threaded console/REPL smoke test ---------------------------------------


def test_mock_flight_chain_threaded_console_smoke(tmp_path: Path) -> None:
    """Runs the real `--console` threading model against the same fixture:
    `_run_console_poll_loop` on a background thread (mirroring `main()`'s
    `--console` wiring exactly, including opening its own thread-local
    `sqlite3.Connection`), while the foreground thread dispatches REPL
    commands via `belief.console.Console`/`_run_console_repl` against the
    same store. Asserts no exception crosses either thread -- this is the
    test that would have caught the cross-thread `sqlite3.ProgrammingError`
    class of bug (`test_logger.py`'s Stage 6/BL-5 regression tests cover the
    single-poll case; this drives the same real functions across the whole
    20-frame fixture)."""
    frames = _load_frames()
    world_model_db = tmp_path / "region.sqlite"
    build_mock_world_model(world_model_db)
    server = MockAircraftLayerServer(frames)
    url = server.start()
    try:
        aircraft_client = AircraftLayerClient(base_url=url)
        runner = ConsolePerceptionRunner(aircraft_client=aircraft_client)
        stop_event = threading.Event()
        poll_thread = threading.Thread(
            target=_run_console_poll_loop,
            args=(
                runner,
                aircraft_client,
                _THEATRE,
                world_model_db,
                0.01,  # tiny poll interval -- exhausts all 20 frames quickly
                stop_event,
            ),
            daemon=True,
        )
        poll_thread.start()
        try:
            # Let the poll thread consume every fixture frame (the mock
            # server holds at the last frame once exhausted, so waiting for
            # last_t_sim to reach the final frame's t_sim is a reliable
            # "all frames consumed" signal, not a race on poll count).
            final_t_sim = frames[-1]["telemetry"]["dcs_model_time_s"]
            deadline = time.monotonic() + _THREAD_JOIN_TIMEOUT_S
            while runner.last_t_sim != final_t_sim and time.monotonic() < deadline:
                time.sleep(0.02)
            assert runner.last_t_sim == final_t_sim, (
                "poll thread did not reach the fixture's final frame within "
                f"{_THREAD_JOIN_TIMEOUT_S}s"
            )

            output = io.StringIO()
            console = Console(store=runner.store, output=output)
            # `_run_console_repl` reads sys.stdin line-by-line until EOF --
            # mirrors test_logger.py's own monkeypatched-stdin pattern.
            stdin = io.StringIO("contacts\nshow CONTACT_1\n")
            real_stdin = sys.stdin
            sys.stdin = stdin
            try:
                _run_console_repl(runner, console, world_model_db, _THEATRE)
            finally:
                sys.stdin = real_stdin
        finally:
            stop_event.set()
            poll_thread.join(timeout=_THREAD_JOIN_TIMEOUT_S)

        assert not poll_thread.is_alive(), (
            f"poll thread failed to stop within {_THREAD_JOIN_TIMEOUT_S}s"
        )

        repl_output = output.getvalue()
        assert "sqlite3.ProgrammingError" not in repl_output
        assert repl_output.strip() != ""
    finally:
        server.stop()
