"""`CalloutScheduler` -- `plans/callout-scheduling/plan.md`, Slice A: the
scheduler itself, fixing the 2026-09-21 cones 2C sortie finding "Callouts
must not be backlogged" on its own (independently shippable -- Slice B
layers report-space aggregation on top, in a separate commit, so this seam
stays revertible without losing the fix below).

**The decision moves to speech time.** `CrewConsole.drain_events` used to
render and acknowledge *every* currently-unacknowledged event on every poll,
handing the whole batch to `_print` at once -- so a callout's text was
frozen the instant `tick()` produced its event, and how long it sat before
being heard was whatever the downstream `AudioPlaybackSender` FIFO queue
happened to be doing. That is exactly the pilot's "12 o'clock when I had
already flown past it several seconds ago." `CalloutScheduler.tick` fixes
this by choosing **at most one** thing to say per call, re-rendering it from
*current* belief the instant it is chosen -- nothing is rendered until the
instant it is spoken, which is the whole fix: there is nothing to go stale,
because nothing exists ahead of being spoken.

**The candidate set is not a queue this module builds or owns.** It is
`store.unacknowledged_events`, filtered and re-read every call -- the belief
store itself is the backlog. `CalloutScheduler` holds only `busy_until_sim`
(a sim-time float) and `_consumed` (a `set[str]` of event ids deliberately
dropped as stale or vanished). No pre-rendered text is ever stored.

**Occupancy is modelled in sim time, never wall clock.** A real
playback-completion signal was rejected outright (see the plan's "Replay
determinism" section): it would have to come back from the Windows box
through `audio-adapter`, does not exist when `--speech-audio` is off, and is
unreproducible under replay -- `body-layer` replays recorded streams and sim
time is authoritative there, never wall clock.
`estimate_speech_duration_s` is a pure function of the rendered string, so
every piece of this module's state is a sim-time float or an id set derived
from events -- no `time.time()`, no thread, no I/O. Replaying the same
recorded stream therefore produces a byte-identical sequence of spoken
lines.

**Priority is an explicitly disposable placeholder.** `callout_priority`'s
first tuple element, `threat_band`, is a constant (`_DEFAULT_THREAT_BAND`)
-- no threat model is built here. The shape is chosen so a real threat band
slots in as that first element later without touching anything else (see
the plan's "Priority" section for the full rationale on each surviving
key: attention, then proximity, then recency).

**No aggregation in this slice.** Every candidate here is spoken as its own
single event, exactly as `route_event` already renders it -- `belief.speech`
is untouched by this commit. Slice B adds `group_candidates`/
`render_group_report` on top, changing only how the candidate list handed
to the priority/render step is built."""

from __future__ import annotations

import math
from dataclasses import dataclass, field
from typing import Final

from belief.contacts import ContactStore
from belief.enrichment import EnrichmentContext
from belief.events import (
    CONTACT_CLASSIFICATION_CHANGED,
    CONTACT_DETECTED,
    CONTACT_REACQUIRED,
    Event,
    EventKind,
)
from belief.speech import route_event
from belief.tools import describe_contact

#: The event kinds `route_event` can actually turn into speech -- every
#: other kind (`CONTACT_LOST`, `CONTACT_ATTENTION_CHANGED`,
#: `CONTACT_CARDINALITY_CHANGED`) has no template and is skipped outright
#: here rather than re-rendered to `None` every poll, unlike the
#: pre-scheduler `drain_events`, which round-tripped every kind through
#: `route_event` regardless.
_TEMPLATED_KINDS: Final[frozenset[EventKind]] = frozenset(
    {CONTACT_DETECTED, CONTACT_REACQUIRED, CONTACT_CLASSIFICATION_CHANGED}
)

#: Shorter than both `EVENT_COOLDOWN_S` (15, `belief/events.py`) and
#: `SCAN_CYCLE_PERIOD_S` (16, `perception/gaze.py`) -- so an expired
#: candidate about something still present is regenerated by the next scan
#: cycle rather than lost for good. Expiring is not losing: an expired
#: candidate is added to `_consumed` and left unacknowledged (see
#: `CalloutScheduler.tick`), so a future brain's `poll_events` still sees
#: the original event.
CALLOUT_MAX_AGE_S: Final[float] = 10.0

#: A breath between lines, and slack absorbing a small under-estimate in
#: `estimate_speech_duration_s` -- see that function's own docstring.
INTER_UTTERANCE_GAP_S: Final[float] = 0.75

#: **Uncalibrated -- needs a live sortie.** ~150 words per minute, the plan's
#: one real guess (`plans/callout-scheduling/plan.md`, "Risks & Unknowns":
#: "Duration estimation drift is the only load-bearing guess"). Isolated
#: here, same "mechanism and calibration never share a commit" posture as
#: `perception/optics.py`'s own provenance comments, so retuning it later
#: never touches `estimate_speech_duration_s`'s mechanism.
SPEECH_RATE_WPS: Final[float] = 2.5

#: **Uncalibrated -- needs a live sortie.** Per-line synthesis/transport
#: overhead, roughly the measured `say` latency from `plans/
#: tts-voice-output/plan.md` Decision 2 -- see `SPEECH_RATE_WPS`'s own note
#: on why this is isolated as its own constant rather than folded into the
#: words-per-second term.
MIN_UTTERANCE_S: Final[float] = 0.6

#: The one line `docs/concept/threat-levels.md` will eventually replace,
#: once coalition inference lands (plan, "Second-order effect"). Every
#: candidate gets the same band today, so this key never actually
#: discriminates between candidates yet -- it exists so `callout_priority`'s
#: tuple shape does not have to change when it does.
_DEFAULT_THREAT_BAND: Final[int] = 0

#: `belief.attention._ATTENTION_RANK`'s ordering, restated here rather than
#: imported -- that name is module-private to `attention.py` (its own
#: docstring: "the one place that ordering is encoded"), and no other
#: module imports it. `callout_priority` needs the same ordering as a
#: ranking key, not as the source of truth for what "higher" means, so a
#: small local restatement (checked against `attention.py`'s table at
#: authorship) is preferable to widening that module's public surface for
#: one caller.
_ATTENTION_PRIORITY_RANK: Final[dict[str, int]] = {
    "ignore": 0,
    "normal": 1,
    "watch": 2,
    "priority": 3,
}


def estimate_speech_duration_s(text: str) -> float:
    """A pure function of `text` alone -- see module docstring's "Occupancy
    is modelled in sim time" note for why this must never consult a real
    playback-completion signal. `SPEECH_RATE_WPS`/`MIN_UTTERANCE_S` are both
    uncalibrated placeholders (their own docstrings say so)."""
    word_count = len(text.split())
    return MIN_UTTERANCE_S + word_count / SPEECH_RATE_WPS


def callout_priority(
    facts: dict[str, object], event: Event, now_sim: float
) -> tuple[int, int, float, float]:
    """`(threat_band, -attention_rank, range_m, -event.t_sim)` -- ascending
    sort order, so the *lowest* tuple is the best candidate. See module
    docstring's "Priority" section for why each surviving key is here:
    `threat_band` is `_DEFAULT_THREAT_BAND` today (a disposable placeholder,
    not a real assessment); `-attention_rank` ranks priority > watch >
    normal > ignore; `range_m` is nearer-first (what goes stale fastest);
    `-event.t_sim` is newer-first (what makes "backlogged" impossible by
    construction -- combined with `CALLOUT_MAX_AGE_S` expiry, an old
    candidate starving is the intended outcome, not a bug).

    `range_m` falls back to `math.inf` (sorts last, never first) when no
    `EnrichmentContext` was supplied -- `facts["relative_now"]` is then
    absent entirely, the module's own absent-not-null convention, and
    there is no proximity signal to rank on."""
    attention = facts.get("attention")
    default_rank = _ATTENTION_PRIORITY_RANK["normal"]
    rank = (
        _ATTENTION_PRIORITY_RANK.get(attention, default_rank)
        if isinstance(attention, str)
        else default_rank
    )
    relative_now = facts.get("relative_now")
    if isinstance(relative_now, dict):
        range_m = relative_now["range_m"]
        assert isinstance(range_m, float)
    else:
        range_m = math.inf
    return (_DEFAULT_THREAT_BAND, -rank, range_m, -event.t_sim)


@dataclass
class CalloutScheduler:
    """Owns speech-time occupancy for one `CrewConsole` -- see module
    docstring. Held as one more `CrewConsole` field; `drain_events`
    delegates to `tick`, `_print` calls `note_urgent` on the
    `bypass_gate=True` path."""

    busy_until_sim: float = 0.0
    _consumed: set[str] = field(default_factory=set, repr=False)

    def note_urgent(self, now_sim: float, text: str) -> None:
        """An urgent (`bypass_gate=True`) line just went out through a path
        this scheduler never chose -- `!inject-urgent`'s test harness, the
        only source of an `UrgentCall` today. `AudioPlaybackSender.
        interrupt` clears the routine queue and kills any in-flight
        playback on the real audio path, so this scheduler must reset its
        own occupancy to the urgent line's own duration rather than
        continuing to believe a routine line the audio layer has already
        destroyed is still playing (plan, "The urgent path")."""
        self.busy_until_sim = now_sim + estimate_speech_duration_s(text)

    def tick(
        self,
        store: ContactStore,
        now_sim: float,
        enrichment: EnrichmentContext | None = None,
    ) -> list[str]:
        """Speak at most one thing, chosen fresh from current belief. See
        module docstring for the full algorithm; this is the plan's
        numbered steps 1-7 in one function (no grouping in this slice --
        step 4's "group" is always a single event here)."""
        if now_sim < self.busy_until_sim:
            return []

        live: list[Event] = []
        for event in store.unacknowledged_events:
            if event.kind not in _TEMPLATED_KINDS or event.id in self._consumed:
                continue
            if now_sim - event.t_sim > CALLOUT_MAX_AGE_S:
                self._consumed.add(event.id)
                continue
            live.append(event)

        if not live:
            return []

        scored: list[tuple[tuple[int, int, float, float], Event]] = []
        for event in live:
            result = describe_contact(
                store, event.contact_id, now_sim, enrichment=enrichment
            )
            if result is None:
                self._consumed.add(event.id)
                continue
            scored.append((callout_priority(result["facts"], event, now_sim), event))

        scored.sort(key=lambda item: item[0])

        for _, event in scored:
            speech = route_event(store, event, now_sim, enrichment)
            if speech is None:
                self._consumed.add(event.id)
                continue
            self.busy_until_sim = (
                now_sim
                + estimate_speech_duration_s(speech.text)
                + INTER_UTTERANCE_GAP_S
            )
            return [speech.text]

        return []
