--[[
PETROVICH DETECTION PROBE -- not the production export script.

Self-contained: does NOT connect to the collector. Appends to
Logs\aircraft_layer_probe_detect.log. Deploy by copying to
`Saved Games\DCS\Scripts\Export.lua`, fly, then read the log back.

BACKGROUND. The command investigation (2026-09-11, runs 1-5) settled the
EFFECTOR question: the 9K113 sight can be pointed from Export.lua with
    GetDevice(7):SetCommand(3061, azimuth_deg / 60.0)
and read back from arg 874. See
aircraft-layer/research/2026-09-11-command-injection-surface.md.

What that did NOT show is whether pointing the sight influences what
PETROVICH DETECTS. That is a different question and this probe is step one of
it: before testing whether we can change detection, we must be able to SEE
detection from outside at all.

WHAT WE KNOW GOING IN
- Petrovich's readout is indicator 6 (`ccHelperAIIndicator_Mi24`). Its page
  declares real text elements: `mode_text` (his current MODE), `hdg_text`,
  `az_text`, `el_text`, a scrollable target list (`show_list`,
  `list_red_arrow[-2..+2]`, `middle_list_text` and siblings), and colour-coded
  holders (red/yellow/beige/green) that plausibly encode classification.
- In all five command-probe runs `list_indication(6)` came back EMPTY -- only
  a childless `crosshair`. The page renders; the list is simply not shown.
- Prior research (forum, thread 388039) claims the list is "generated by
  Petrovich AI when using missiles", i.e. gated on weapon mode -- which is the
  concrete form of the player-mode-vs-AI-mode question.

SO THIS PROBE IS PASSIVE. It issues no commands. It watches indicator 6 and
the AI wheel, dumps them WHENEVER THEY CHANGE, and stamps each change with the
full gating state, so the conditions under which Petrovich's detection becomes
externally visible can be read straight off the log.

HOW TO FLY IT
Fly a mission with real ground targets in view, and deliberately vary:
  1. Weapon selector (arg 523: OFF / GM / URS / NPU) -- especially URS
     (missiles), the state the forum claim points at.
  2. Armament power (673), fire control (551), missile power (773).
  3. The Petrovich command wheel: open it (LCtrl+V) and issue real commands --
     search, attack, etc. Hold it open a few seconds so indicator 10 is caught
     populated; it has never yet been seen with content.
  4. Sight state: doors open, NABL on, and slew the sight onto and off a target.
  5. Both seats if convenient -- pilot and operator.
Narrate nothing; the log timestamps everything. Just make sure each condition
is held for a few seconds.

Delete this file once the detection question is settled.
]]

local LOG_PATH = lfs.writedir() .. "Logs\\aircraft_layer_probe_detect.log"

local log_file = nil
local function log(msg)
    if log_file == nil then
        local ok, f = pcall(io.open, LOG_PATH, "a")
        if not ok or f == nil then return end
        log_file = f
    end
    log_file:write(os.date("%H:%M:%S") .. " " .. tostring(msg) .. "\n")
    log_file:flush()
end

local function try(label, fn, ...)
    local ok, a = pcall(fn, ...)
    if not ok then
        log(string.format("  %-28s ERROR: %s", label, tostring(a)))
        return nil
    end
    return a
end

local function safe_index(obj, key)
    local ok, v = pcall(function() return obj[key] end)
    if not ok then return nil end
    return v
end

-- ---------------------------------------------------------------- constants
local DEV_MAINPANEL = 0

local IND_9K113    = 0
local IND_HELPERAI = 6
local IND_AI_WHEEL = 10

-- Everything plausibly gating Petrovich's detection readout, read every
-- snapshot so a change in indicator 6 can be attributed to a state change.
local WATCH_ARGS = {
    -- weapon system (the forum claim's gate)
    {523, "WeapSelect OFF/GM/URS/NPU"},
    {551, "FireControl on/off"},
    {673, "ArmamentPower"},
    {773, "MissilePower URS"},
    {709, "WeaponType A/B"},
    {536, "PUS arming"},
    {963, "LaunchStation"},
    -- 9K113 sight
    {874, "Sight azimuth"},
    {876, "Sight elevation"},
    {775, "Sight doors"},
    {886, "NABL observe"},
    {885, "Sight power"},
    {871, "Sight zoom"},
}

local function read_arg(arg)
    local mp = try("GetDevice(0)", GetDevice, DEV_MAINPANEL)
    if mp == nil then return nil end
    local fn = safe_index(mp, "get_argument_value")
    if type(fn) ~= "function" then return nil end
    return try("get_argument_value", fn, mp, arg)
end

local function state_line()
    local parts = {}
    for _, w in ipairs(WATCH_ARGS) do
        local v = read_arg(w[1])
        if type(v) == "number" then
            parts[#parts + 1] = string.format("%s=%.3f", w[2], v)
        else
            parts[#parts + 1] = string.format("%s=?", w[2])
        end
    end
    return table.concat(parts, "  ")
end

-- ------------------------------------------------------- change detection
-- list_indication returns a big formatted string. Keep the last payload per
-- indicator and only log when it differs -- otherwise the log is unreadable
-- at any useful poll rate.
local last = {}

local function check_indicator(n, label, t)
    local s = try("list_indication", list_indication, n)
    local body = tostring(s)
    if body == last[n] then return false end
    last[n] = body

    log("")
    log(string.format("### t=%.1f  %s (indicator %d) CHANGED  [%d bytes]",
                      t, label, n, #body))
    log("    state: " .. state_line())
    -- trim: these can be long, but the whole point is the content
    if #body > 4000 then
        log(body:sub(1, 4000) .. "\n...<truncated>")
    else
        log(body)
    end
    return true
end

-- ------------------------------------------------------------ driver
local started = false
local t0, last_poll, last_state = nil, -1, -1
local POLL_S  = 0.25     -- change detection rate
local STATE_S = 10.0     -- periodic state heartbeat even with no change

function LuaExportStart()
    log("")
    log("=========================================================")
    log("PETROVICH DETECTION PROBE -- passive, issues no commands")
    log("=========================================================")
    local gd = type(GetDevice)
    log("  GetDevice = " .. gd .. ", list_indication = " .. type(list_indication))
    started = true
end

function LuaExportStop()
    log("detection probe: stopped.")
    if log_file then log_file:close() log_file = nil end
end

function LuaExportActivityNextEvent(t)
    return t + 1.0
end

function LuaExportAfterNextFrame()
    if not started then return end
    local t = try("LoGetModelTime", LoGetModelTime)
    if type(t) ~= "number" then return end
    if t0 == nil then
        t0 = t
        last_poll, last_state = t, t
        log("  first frame; dumping all indicators once as a baseline")
        for n = 0, 11 do
            local s = tostring(try("list_indication", list_indication, n))
            log(string.format("  indicator %2d: %d bytes%s", n, #s,
                              (#s > 70) and "  (has content)" or "  (empty)"))
            last[n] = s
        end
        log("  state: " .. state_line())
        return
    end

    if (t - last_poll) >= POLL_S then
        last_poll = t
        check_indicator(IND_HELPERAI, "PETROVICH", t)
        check_indicator(IND_AI_WHEEL, "AI WHEEL", t)
        check_indicator(IND_9K113,    "9K113 SIGHT", t)
    end

    if (t - last_state) >= STATE_S then
        last_state = t
        log(string.format("t=%.1f  %s", t, state_line()))
    end
end
